manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lily
      url-base: https://github.com/lilyinstarlight
  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: 1ae0eb5ce8adafcec993e6fb8f4eeb6f818a7772  # v3.2.0+zmk-fixes
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
          - sof
    - name: zmk
      remote: lily
      revision: b551117c76c9f0daca298dddf5b26c21e46d872b  # feature/sofle_rgb_keyhive
      import: app/west.yml
  self:
    path: config
