name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - run: nix -vL --show-trace flake check

      - run: nix -vL --show-trace build

      - uses: actions/upload-artifact@v3
        with:
          name: zmk_firmware
          path: result
